USE [master]
GO
/****** Object:  Database [ForoSQL]    Script Date: 28/10/2023 22:22:17 ******/
CREATE DATABASE [ForoSQL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ForoSQL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.DATAWAREHOSE\MSSQL\DATA\ForoSQL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ForoSQL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.DATAWAREHOSE\MSSQL\DATA\ForoSQL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ForoSQL] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ForoSQL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ForoSQL] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ForoSQL] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ForoSQL] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ForoSQL] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ForoSQL] SET ARITHABORT OFF 
GO
ALTER DATABASE [ForoSQL] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ForoSQL] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ForoSQL] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ForoSQL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ForoSQL] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ForoSQL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ForoSQL] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ForoSQL] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ForoSQL] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ForoSQL] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ForoSQL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ForoSQL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ForoSQL] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ForoSQL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ForoSQL] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ForoSQL] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ForoSQL] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ForoSQL] SET RECOVERY FULL 
GO
ALTER DATABASE [ForoSQL] SET  MULTI_USER 
GO
ALTER DATABASE [ForoSQL] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ForoSQL] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ForoSQL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ForoSQL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ForoSQL] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ForoSQL] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ForoSQL', N'ON'
GO
ALTER DATABASE [ForoSQL] SET QUERY_STORE = OFF
GO
USE [ForoSQL]
GO
/****** Object:  Table [dbo].[Alumno]    Script Date: 28/10/2023 22:22:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Alumno](
	[idAlumno] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Apellido] [varchar](50) NOT NULL,
	[DUI] [varchar](100) NOT NULL,
	[FechaNacimiento] [varchar](100) NOT NULL,
	[Correo] [varchar](150) NOT NULL,
	[Direccion] [varchar](150) NOT NULL,
	[Telefono] [varchar](100) NOT NULL,
 CONSTRAINT [PK_Alumno] PRIMARY KEY CLUSTERED 
(
	[idAlumno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AlumnoGrupo]    Script Date: 28/10/2023 22:22:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AlumnoGrupo](
	[idAlumno] [int] NOT NULL,
	[idGrupo] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Asignatura]    Script Date: 28/10/2023 22:22:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Asignatura](
	[idAsignatura] [int] IDENTITY(1,1) NOT NULL,
	[Asignatura] [varchar](100) NOT NULL,
	[idCarrera] [int] NOT NULL,
 CONSTRAINT [PK_Asignatura] PRIMARY KEY CLUSTERED 
(
	[idAsignatura] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Carrera]    Script Date: 28/10/2023 22:22:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Carrera](
	[idCarrera] [int] NOT NULL,
	[Carrera] [varchar](100) NOT NULL,
 CONSTRAINT [PK_Carrera] PRIMARY KEY CLUSTERED 
(
	[idCarrera] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Docente]    Script Date: 28/10/2023 22:22:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Docente](
	[idDocente] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Apellido] [varchar](50) NOT NULL,
	[Direccion] [varchar](150) NOT NULL,
	[Telefono] [varchar](50) NOT NULL,
	[CorreoInstitucional] [varchar](150) NOT NULL,
	[DUI] [varchar](100) NOT NULL,
 CONSTRAINT [PK_Docente] PRIMARY KEY CLUSTERED 
(
	[idDocente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Evaluacion]    Script Date: 28/10/2023 22:22:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Evaluacion](
	[idEvaluacion] [int] IDENTITY(1,1) NOT NULL,
	[Evaluacion] [varchar](150) NOT NULL,
	[Porcentaje] [decimal](18, 0) NOT NULL,
	[idAsignatura] [int] NOT NULL,
 CONSTRAINT [PK_Evaluacion] PRIMARY KEY CLUSTERED 
(
	[idEvaluacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Grupo]    Script Date: 28/10/2023 22:22:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Grupo](
	[idGrupo] [int] IDENTITY(1,1) NOT NULL,
	[idDocente] [int] NOT NULL,
	[idAsignatura] [int] NOT NULL,
 CONSTRAINT [PK_Grupo] PRIMARY KEY CLUSTERED 
(
	[idGrupo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Nota]    Script Date: 28/10/2023 22:22:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Nota](
	[idNota] [int] IDENTITY(1,1) NOT NULL,
	[Nota] [decimal](18, 0) NOT NULL,
	[Ciclo] [int] NOT NULL,
	[idEvaluacion] [int] NOT NULL,
	[idAlumno] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AlumnoGrupo]  WITH CHECK ADD  CONSTRAINT [FK_AlumnoGrupo_Alumno] FOREIGN KEY([idAlumno])
REFERENCES [dbo].[Alumno] ([idAlumno])
GO
ALTER TABLE [dbo].[AlumnoGrupo] CHECK CONSTRAINT [FK_AlumnoGrupo_Alumno]
GO
ALTER TABLE [dbo].[AlumnoGrupo]  WITH CHECK ADD  CONSTRAINT [FK_AlumnoGrupo_Grupo] FOREIGN KEY([idGrupo])
REFERENCES [dbo].[Grupo] ([idGrupo])
GO
ALTER TABLE [dbo].[AlumnoGrupo] CHECK CONSTRAINT [FK_AlumnoGrupo_Grupo]
GO
ALTER TABLE [dbo].[Asignatura]  WITH CHECK ADD  CONSTRAINT [FK_Asignatura_Carrera] FOREIGN KEY([idCarrera])
REFERENCES [dbo].[Carrera] ([idCarrera])
GO
ALTER TABLE [dbo].[Asignatura] CHECK CONSTRAINT [FK_Asignatura_Carrera]
GO
ALTER TABLE [dbo].[Evaluacion]  WITH CHECK ADD  CONSTRAINT [FK_Evaluacion_Asignatura] FOREIGN KEY([idAsignatura])
REFERENCES [dbo].[Asignatura] ([idAsignatura])
GO
ALTER TABLE [dbo].[Evaluacion] CHECK CONSTRAINT [FK_Evaluacion_Asignatura]
GO
ALTER TABLE [dbo].[Grupo]  WITH CHECK ADD  CONSTRAINT [FK_Grupo_Asignatura] FOREIGN KEY([idAsignatura])
REFERENCES [dbo].[Asignatura] ([idAsignatura])
GO
ALTER TABLE [dbo].[Grupo] CHECK CONSTRAINT [FK_Grupo_Asignatura]
GO
ALTER TABLE [dbo].[Grupo]  WITH CHECK ADD  CONSTRAINT [FK_Grupo_Docente] FOREIGN KEY([idDocente])
REFERENCES [dbo].[Docente] ([idDocente])
GO
ALTER TABLE [dbo].[Grupo] CHECK CONSTRAINT [FK_Grupo_Docente]
GO
ALTER TABLE [dbo].[Nota]  WITH CHECK ADD  CONSTRAINT [FK_Nota_Alumno] FOREIGN KEY([idAlumno])
REFERENCES [dbo].[Alumno] ([idAlumno])
GO
ALTER TABLE [dbo].[Nota] CHECK CONSTRAINT [FK_Nota_Alumno]
GO
ALTER TABLE [dbo].[Nota]  WITH CHECK ADD  CONSTRAINT [FK_Nota_Evaluacion] FOREIGN KEY([idEvaluacion])
REFERENCES [dbo].[Evaluacion] ([idEvaluacion])
GO
ALTER TABLE [dbo].[Nota] CHECK CONSTRAINT [FK_Nota_Evaluacion]
GO
USE [master]
GO
ALTER DATABASE [ForoSQL] SET  READ_WRITE 
GO
